version: '2'
services:
  public: 
    build:
      context: ./public
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.3 
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html

  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.10
    ports:
      - "8085:80"
    volumes:
      - ./frontend:/var/www/html

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    tty: true 
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.2
    ports:
      - "3304:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
  
  anuncios:
    build:
      context: ./anuncios
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.5
    ports:
      - "8081:80"
    volumes:
      - ./anuncios:/var/www/html

  login:
    build:
      context: ./login
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.4
    ports:
      - "8082:81"
    volumes:
      - ./login:/var/www/html

  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.6
    ports:
      - "8083:80"
    volumes:
      - ./backoffice:/var/www/html

  resultados:
    build:
      context: ./resultados
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.7
    ports:
      - "8084:80"
    volumes:
      - ./resultados:/var/www/html

networks:
  aplicacion:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.48.0/20
         gateway: 192.168.48.1
