version: '2'
services:

  frontend: 
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./frontend:/var/www/html

  bd:
    container_name: BaseDeDatos
    image: mysql:5.7
    tty: true
    ports:
      - "3306:3306"
    restart: unless-stopped 
    environment:
      - MYSQL_ROOT_PASSWORD=43018141
      - MYSQL_USER=gustavo.guerrero
      - MYSQL_PASSWORD=43018141
      - MYSQL_DATABASE=teikucodewar
    volumes:
      - ./db/mysql:/var/lib/mysql

  anuncios:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./anuncios:/var/www/html

  login:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./login:/var/www/html

  backoffice:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./backoffice:/var/www/html

  resultados:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - ./resultados:/var/www/html