version: '2'
services:
  mvc: 
    build:
      context: ./phpCapas
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.3 
    ports:
      - "8080:80"
    volumes:
      - ./phpCapas:/var/www/html

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true 
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.2
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql:/var/lib/mysql
  
  anuncios:
    build:
      context: ./appAnuncios
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.5
    ports:
      - "8081:80"
    volumes:
      - ./appAnuncios:/var/www/html

  login:
    build:
      context: ./appLogin
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.4
    ports:
      - "8082:81"
    volumes:
      - ./appLogin:/var/www/html

  admin:
    build:
      context: ./appAdmin
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.6
    ports:
      - "8083:80"
    volumes:
      - ./appAdmin:/var/www/html

  resultados:
    build:
      context: ./appResultados
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    networks:
      aplicacion:
        ipv4_address: 192.168.48.7
    ports:
      - "8084:80"
    volumenes:
      - ./appResultados:/var/www/html

networks:
  aplicacion:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.48.0/20
         gateway: 192.168.48.1