version: '2'
services:
  public: 
    build:
      context: ./public
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html

  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./frontend:/var/www/html

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    tty: true 
    restart: unless-stopped
    ports:
      - "3305:3306"
    volumes:
      - $PWD/db/mysql:/var/lib/mysql
    command: [--ignore-db-dir=lost+found]  
  
  anuncios:
    build:
      context: ./anuncios
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./anuncios:/var/www/html

  login:
    build:
      context: ./login
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./login:/var/www/html

  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./backoffice:/var/www/html

  resultados:
    build:
      context: ./resultados
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - ./resultados:/var/www/html